wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1670608355.876142
    t:
      1:
      - 1
      - 11
      - 33
      - 40
      - 49
      - 55
      2:
      - 1
      - 5
      - 11
      - 33
      - 40
      - 49
      - 51
      - 53
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.13.6
      6: 4.24.0
      8:
      - 1
      - 4
      - 5
